info:
  name: Delete checkout configuration
  type: http
  seq: 4

http:
  method: DELETE
  url: "{{baseUrl}}/api/checkout/configuration/ui?an=12872182"
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: application/json
  params:
    - name: an
      value: "12872182"
      type: query
    - name: accountName
      value: "{{accountName}}"
      type: path
    - name: environment
      value: "{{environment}}"
      type: path
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[DELETE]::/api/checkout/configuration/ui - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  >📘 This functionality is in the beta stage and can be discontinued at any moment at VTEX's discretion. VTEX will not be responsible for any instabilities caused by its use or discontinuity. If you have any questions, please contact [our Support Center](https://support.vtex.com/hc/en-us/requests).

  Deletes an existing checkout configuration from a store. This endpoint allows developers to remove a checkout configuration that is no longer needed or has become obsolete.

  ## Permissions

  This endpoint does not require [permissions](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3).

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `accountName` | path | Name of the VTEX account. Used as part of the URL |
  | `environment` | path | Environment to use. Used as part of the URL. (This can only be one of vtexcommercestable) |
  | `an` | query | (Required) Checkout configuration ID. |
  | `Content-Type` | header | (Required) Type of the content being sent. |
  | `Accept` | header | (Required) HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand. |
