info:
  name: Configure external price source
  type: http
  seq: 2

http:
  method: PUT
  url: "{{baseUrl}}/api/pricing-hub/prices/config"
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
  params:
    - name: an
      value: apiexamples
      type: query
      disabled: true
    - name: environment
      value: "{{environment}}"
      type: path
  body:
    type: json
    data: |-
      {
        "active": true,
        "appName": "apiexamples_app_name"
      }
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[PUT]::/api/pricing-hub/prices/config - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  >⚠️ This API has been deprecated. If you need to associate prices with customers, we recommend using the [Audience API](https://developers.vtex.com/docs/api-reference/audience-api).

  This route facilitates setting up an external price source in Pricing Hub. It also allows you to activate or deactivate that source in a given account.

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `environment` | path | Environment to use. Used as part of the URL. (This can only be one of vtexcommercestable) |
  | `an` | query | Name of the VTEX account. |
  | `Accept` | header | (Required) HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand. |
  | `Content-Type` | header | (Required) Describes the type of the content being sent. |
