info:
  name: Update order form configuration
  type: http
  seq: 3

http:
  method: PATCH
  url: "{{baseUrl}}/api/checkout/pvt/configuration/orderForm"
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: application/json
  params:
    - name: individualShippingEstimates
      value: "true"
      type: query
      disabled: true
  body:
    type: json
    data: |-
      {
        "paymentConfiguration": {
          "requiresAuthenticationForPreAuthorizedPaymentOption": false
        },
        "taxConfiguration": null,
        "minimumQuantityAccumulatedForItems": 1,
        "decimalDigitsPrecision": 2,
        "minimumValueAccumulated": null,
        "apps": null,
        "allowMultipleDeliveries": null,
        "allowManualPrice": null
      }
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[PATCH]::/api/checkout/pvt/configuration/orderForm - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

        test("[PATCH]::/api/checkout/pvt/configuration/orderForm - Response has empty Body", function () {
          const data = res.getBody();
          expect(data === undefined || data === null || data === "").to.be.true;
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Determines settings that will apply to every orderForm in the account.


  For example, if you create an app using this request, every orderForm of this account will have the custom fields created though it.


  >ℹ️ Always retrieve the current configuration before performing an update to ensure that you are modifying only the properties you want. Otherwise, old values can be overwritten. To retrieve the current configuration, use the request [Get orderForm configuration](https://developers.vtex.com/docs/api-reference/checkout-api#get-/api/checkout/pvt/configuration/orderForm).

  ## Permissions

  Any user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:

  | **Product** | **Category** | **Resource** |
  | --------------- | ----------------- | ----------------- |
  | Checkout | CheckoutResources | **Save OrderForm Configuration** |

  There are no applicable [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) for this resource list. You must [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) and add at least one of the resources above in order to use this endpoint.To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).

  >❗ To prevent integrations from having excessive permissions, consider the [best practices for managing API keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm) when assigning License Manager roles to integrations.

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `individualShippingEstimates` | query | Shows the product's estimated shipping date in the `shippingEstimate` field from the `orderForm`. |
  | `Content-Type` | header | (Required) Type of the content being sent. |
  | `Accept` | header | (Required) HTTP Client Negotiation _Accept_ Header. Indicates the types of responses the client can understand. |
