info:
  name: Edit Subscriptions settings
  type: http
  seq: 2

http:
  method: POST
  url: "{{baseUrl}}/settings"
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: application/json
  params:
    - name: accountName
      value: "{{accountName}}"
      type: path
    - name: environment
      value: "{{environment}}"
      type: path
  body:
    type: json
    data: |-
      {
        "slaOption": "NONE",
        "defaultSla": null,
        "isUsingV3": true,
        "onMigrationProcess": false,
        "executionHourInUtc": 9,
        "workflowVersion": "1.1",
        "deliveryChannels": [],
        "randomIdGeneration": false,
        "isMultipleInstallmentsEnabledOnCreation": false,
        "isMultipleInstallmentsEnabledOnUpdate": false,
        "orderCustomDataAppId": null,
        "postponeExpiration": false,
        "manualPriceAllowed": false,
        "useItemPriceFromOriginalOrder": false
      }
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        const Ajv = require("ajv");
        const addFormats = require("ajv-formats");
        const ajv = new Ajv({ allErrors: true, strict: false });
        addFormats(ajv);

        test("[POST]::/settings - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

        test("[POST]::/settings - Content-Type is application/json", function () {
          expect(String(res.getHeader("content-type"))).to.include("application/json");
        });

        test("[POST]::/settings - Response has JSON Body", function () {
          const data = res.getBody();
          expect(data).to.not.be.undefined;
          expect(data).to.not.be.null;
        });

        test("[POST]::/settings - Schema is valid", function () {
          const schema = {"title":"","description":"Subscriptions settings","type":"object","required":["slaOption","defaultSla","isUsingV3","onMigrationProcess","executionHourInUtc","workflowVersion","deliveryChannels","randomIdGeneration","isMultipleInstallmentsEnabledOnCreation","isMultipleInstallmentsEnabledOnUpdate","orderCustomDataAppId","postponeExpiration","manualPriceAllowed","useItemPriceFromOriginalOrder"],"properties":{"slaOption":{"title":"slaOption","description":"Delivery method.","type":"string","default":"","example":"NONE"},"defaultSla":{"title":"defaultSla","description":"Default delivery method.","type":["string","null"],"default":null,"example":null},"isUsingV3":{"title":"isUsingV3","description":"Indicates whether or not Subscriptions V3 is enabled.","type":"boolean","default":false,"example":true},"onMigrationProcess":{"title":"onMigrationProcess","description":"Indicates whether or not the account is in the migration process to Subscriptions V3.","type":"boolean","default":false,"example":false},"executionHourInUtc":{"title":"executionHourInUtc","description":"Indicates the time future subscription orders will be generated.","type":"integer","default":0,"example":9},"workflowVersion":{"title":"workflowVersion","description":"Workflow version.","type":"string","default":"","example":"1.1"},"deliveryChannels":{"title":"deliveryChannels","description":"Array containing delivery channels.","type":"array","default":[],"items":{"title":"","description":"Type of delivery channel. The values that are possible are: `pickup-in-point` for pickup point and `delivery` for regular delivery.","type":"string","default":"","example":"delivery"},"example":"delivery"},"randomIdGeneration":{"title":"randomIdGeneration","description":"Defines whether or not the subscription order IDs will be randomly generated.","type":"boolean","default":false,"example":false},"isMultipleInstallmentsEnabledOnCreation":{"title":"isMultipleInstallmentsEnabledOnCreation","description":"Defines whether or not multiple installments are enabled when a subscription is created.","type":"boolean","default":false,"example":false},"isMultipleInstallmentsEnabledOnUpdate":{"title":"isMultipleInstallmentsEnabledOnUpdate","description":"Defines whether or not multiple installments are enabled when a subscription is updated.","type":"boolean","default":false,"example":false},"orderCustomDataAppId":{"title":"orderCustomDataAppId","description":"When filled, this field passes along the `customData` infomration in the order to the future recurrent subscription orders.","type":"string","default":null,"example":null},"postponeExpiration":{"title":"postponeExpiration","description":"Defines whether or not the expiration of subscriptions can be postponed.","type":"boolean","default":false,"example":false},"manualPriceAllowed":{"title":"manualPriceAllowed","description":"When set to `true`, this property enables manual price configuration in subscription items. This is valid for all existing subscriptions, provided that there is a manual price configured and that `isUsingV3` is `true`.","type":"boolean","default":false,"example":false},"useItemPriceFromOriginalOrder":{"title":"useItemPriceFromOriginalOrder","description":"When set to `true`, this property enables using the manual price for each item from the original subscription order. This is only valid for new subscriptions, created from the moment this configuration is enabled. For this to work, it is mandatory that the `manualPriceAllowed` property is set to `true` and that `isUsingV3` is `true`.","type":"boolean","default":false,"example":false}},"example":{"slaOption":"NONE","defaultSla":null,"isUsingV3":true,"onMigrationProcess":false,"executionHourInUtc":9,"workflowVersion":"1.1","deliveryChannels":["delivery"],"randomIdGeneration":false,"isMultipleInstallmentsEnabledOnCreation":false,"isMultipleInstallmentsEnabledOnUpdate":false,"orderCustomDataAppId":null,"postponeExpiration":false,"manualPriceAllowed":false,"useItemPriceFromOriginalOrder":false}};
          const validate = ajv.compile(schema);
          const valid = validate(res.getBody());
          expect(valid, JSON.stringify(validate.errors)).to.be.true;
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Edits Subscriptions settings in your store.

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `accountName` | path | Name of the VTEX account. Used as part of the URL |
  | `environment` | path | Environment to use. Used as part of the URL. (This can only be one of vtexcommercestable) |

  ## Example response (`200`)

  ```json
  {
    "slaOption": "NONE",
    "defaultSla": null,
    "isUsingV3": true,
    "onMigrationProcess": false,
    "executionHourInUtc": 9,
    "workflowVersion": "1.1",
    "deliveryChannels": [],
    "randomIdGeneration": false,
    "isMultipleInstallmentsEnabledOnCreation": false,
    "isMultipleInstallmentsEnabledOnUpdate": false,
    "orderCustomDataAppId": null,
    "postponeExpiration": false,
    "manualPriceAllowed": false,
    "useItemPriceFromOriginalOrder": false
  }
  ```
