info:
  name: Update Subscription settings
  type: http
  seq: 10

http:
  method: PUT
  url: "{{baseUrl}}/subscriptions/settings"
  headers:
    - name: Content-Type
      value: application/json
  params:
    - name: accountName
      value: "{{accountName}}"
      type: path
    - name: environment
      value: "{{environment}}"
      type: path
  body:
    type: json
    data: |-
      {
        "salesChannel": "1",
        "defaultSLA": "Normal"
      }
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[PUT]::/subscriptions/settings - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Updates the Subscriptions' (formerly Recurrence) settings of your store by salesChannel and defaultSLA.

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `accountName` | path | Name of the VTEX account. Used as part of the URL |
  | `environment` | path | Environment to use. Used as part of the URL. (This can only be one of vtexcommercestable) |
