info:
  name: Configure seller account
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/seller-register/pvt/sellers"
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
  params:
    - name: accountName
      value: apiexamples
      type: path
    - name: environment
      value: vtexcommercestable
      type: path
  body:
    type: json
    data: |-
      {
        "id": "seller123",
        "name": "Seller Name",
        "isActive": true,
        "fulfillmentEndpoint": "http://{SellerName}.vtexcommercestable.com.br/api/fulfillment?&sc={TradePolicyID}",
        "allowHybridPayments": false,
        "taxCode": "34444",
        "email": "seller@email.com",
        "description": "Seller A, from the B industry.",
        "sellerCommissionConfiguration": {
          "productCommissionPercentage": 3,
          "freightCommissionPercentage": 4
        },
        "isBetterScope": true,
        "sellerType": 1,
        "availableSalesChannels": [
          {
            "isSelected": true,
            "id": 1,
            "name": "Principal store"
          },
          {
            "isSelected": true,
            "id": 2,
            "name": "Third"
          },
          {
            "isSelected": true,
            "id": 3,
            "name": "Marketplaces"
          }
        ],
        "CSCIdentification": "cscidentification 123",
        "account": "partner01",
        "channel": "channel name",
        "salesChannel": "1",
        "isVtex": true,
        "score": 0,
        "exchangeReturnPolicy": "Describe exchange and returns policy",
        "deliveryPolicy": "Describe delivery policy",
        "securityPrivacyPolicy": "Our marketplace ensures that all transactions are encrypted with SSL technology, and we adhere to strict privacy standards to protect both sellers and buyers. Personal data is only shared with authorized parties to facilitate order processing and delivery, and we do not sell or disclose personal information to third parties without consent.",
        "fulfillmentSellerId": "seller1",
        "user": "integrationHubUserName",
        "password": "integrationHubPassword",
        "catalogSystemEndpoint": "https://apiexamples.vtexcommercestable.com.br/api/catalog_system/",
        "trustPolicy": "AllowEmailSharing",
        "groups": [
          {
            "groups": [
              {
                "name": "long tail"
              },
              {
                "name": "franchise accounts"
              }
            ]
          }
        ]
      }
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[POST]::/seller-register/pvt/sellers - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  This endpoint is used by marketplace operators to configure the accounts of sellers that have already accepted the invitation to join their marketplaces. 

  For marketplaces to [add sellers](https://help.vtex.com/en/tutorial/adding-a-seller--tutorials_392) without the [Seller Invite](https://help.vtex.com/en/tutorial/marketplace-invited-sellers--6rb2FkcslmDueJ689Ulb9A) feature, call this endpoint directly. 

  This call includes all the information a seller needs to activate their account. 

  ## Permissions

  Any user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:

  | **Product** | **Category** | **Resource** |
  | --------------- | ----------------- | ----------------- |
  | Seller Register | Seller Administration | **Save Seller** |

  You can [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) with that resource or use one of the following [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy):

  | **Role** | **Resource** | 
  | --------------- | ----------------- | 
  | Seller manager | Save Seller |

  >❗ Assigning a [predefined role](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) to users or application keys usually grants permission to multiple [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see [Best practices for using application keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm).

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `accountName` | path | (Required) Name of the VTEX account that belongs to the marketplace. The notification will be posted into this account. |
  | `environment` | path | (Required) Environment to use. Used as part of the URL. |
  | `Accept` | header | (Required) HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand. |
  | `Content-Type` | header | (Required) Type of the content being sent. |
