info:
  name: Create or update freight values
  type: http
  seq: 1

http:
  method: POST
  url: "{{baseUrl}}/api/logistics/pvt/configuration/freights/:carrierId/values/update"
  headers:
    - name: Content-Type
      value: application/json
    - name: Accept
      value: application/json
  params:
    - name: carrierId
      value: carrier123
      type: path
  body:
    type: json
    data: |-
      [
        {
          "absoluteMoneyCost": "1.00",
          "country": "BRA",
          "maxVolume": 1000000000,
          "operationType": 1,
          "pricePercent": 10,
          "pricePercentByWeight": 0,
          "timeCost": "2.00:00:00",
          "weightEnd": 1000,
          "weightStart": 1,
          "zipCodeEnd": "1234500",
          "zipCodeStart": "1000000",
          "polygon": "polygon2"
        }
      ]
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[POST]::/api/logistics/pvt/configuration/freights/:carrierId/values/update - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Creates or updates freight values for your store's carriers. Learn more in [Shipping rate template](https://help.vtex.com/en/tutorial/shipping-rate-template--tutorials_127).

  ## Permissions

  Any user or [API key](https://developers.vtex.com/docs/guides/api-authentication-using-api-keys) must have at least one of the appropriate [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3) to be able to successfully run this request. Otherwise they will receive a status code `403` error. These are the applicable resources for this endpoint:

  | **Product** | **Category** | **Resource** |
  | --------------- | ----------------- | ----------------- |
  | Logistics | Logistics access | **Logistics full access** |
  | Logistics | Logistics access | **Logistics shipping full access** |

  You can [create a custom role](https://help.vtex.com/en/tutorial/roles--7HKK5Uau2H6wxE1rH5oRbc#creating-a-role) with that resource or use one of the following [predefined roles](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy):

  | **Role** | **Resource** | 
  | --------------- | ----------------- | 
  | Logistics - Full access | Logistics full access |
  | OMS - Full access | Logistics full access |
  | Logistics - Full access | Logistics shipping full access |
  | OMS - Full access | Logistics shipping full access |

  >❗ Assigning a [predefined role](https://help.vtex.com/en/tutorial/predefined-roles--jGDurZKJHvHJS13LnO7Dy) to users or application keys usually grants permission to multiple [License Manager resources](https://help.vtex.com/en/tutorial/license-manager-resources--3q6ztrC8YynQf6rdc6euk3). If some of these permissions are not necessary, consider creating a custom role instead. For more information regarding security, see [Best practices for using application keys](https://help.vtex.com/en/tutorial/best-practices-api-keys--7b6nD1VMHa49aI5brlOvJm). To learn more about machine authentication at VTEX, see [Authentication overview](https://developers.vtex.com/docs/guides/authentication).

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `carrierId` | path | (Required) Carrier ID. |
  | `Content-Type` | header | (Required) Type of the content being sent. |
  | `Accept` | header | (Required) HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand. |
