info:
  name: Delete hook configuration
  type: http
  seq: 3

http:
  method: DELETE
  url: "{{baseUrl}}/api/orders/hook/config"
  headers:
    - name: Accept
      value: application/json
    - name: Content-Type
      value: application/json
  auth: inherit

runtime:
  scripts:
    - type: tests
      code: |-
        test("[DELETE]::/api/orders/hook/config - Status code is 2xx", function () {
          expect(res.getStatus()).to.be.at.least(200);
          expect(res.getStatus()).to.be.below(300);
        });

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5

docs: |-
  Deletes a given hook configuration.


  Learn more with the [orders hook guide](https://developers.vtex.com/vtex-rest-api/docs/orders-feed#hook).

  ## Parameters

  | Name | In | Description |
  | --- | --- | --- |
  | `Accept` | header | (Required) HTTP Client Negotiation Accept Header. Indicates the types of responses the client can understand. |
  | `Content-Type` | header | (Required) Type of the content being sent. |
